org: vetsinen
app: node-aws-telebot
service: node-aws-telebot

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  start:
    handler: handler.start
    events:
      - http:
          path: webhook
          method: post
          cors: true

